[project]
name = "uniswap-v3-xrpl"
version = "0.1.0"

[build]
source = "contract/src/lib.rs"
target = "wasm32-unknown-unknown"

[networks.local]
url = "ws://localhost:6006"
network_id = 63456
faucet_url = "http://localhost:8080/faucet"

[networks.alphanet]
url = "wss://alphanet.nerdnest.xyz"
network_id = 21465
faucet_url = "https://alphanet.faucet.nerdnest.xyz/accounts"
