# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent_router.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13intent_router.proto\x12\x0cintentrouter\"\'\n\tParameter\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"6\n\rIntentRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x82\x01\n\x0eIntentResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05scope\x18\x02 \x01(\t\x12+\n\nparameters\x18\x03 \x03(\x0b\x32\x17.intentrouter.Parameter\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x10\n\x08is_valid\x18\x05 \x01(\x08\x32[\n\x0cIntentRouter\x12K\n\x0e\x43lassifyIntent\x12\x1b.intentrouter.IntentRequest\x1a\x1c.intentrouter.IntentResponseB;Z9github.com/ajhavlin/BSA-Hackathon/llm-orchestration/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_router_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/ajhavlin/BSA-Hackathon/llm-orchestration/proto'
  _globals['_PARAMETER']._serialized_start=37
  _globals['_PARAMETER']._serialized_end=76
  _globals['_INTENTREQUEST']._serialized_start=78
  _globals['_INTENTREQUEST']._serialized_end=132
  _globals['_INTENTRESPONSE']._serialized_start=135
  _globals['_INTENTRESPONSE']._serialized_end=265
  _globals['_INTENTROUTER']._serialized_start=267
  _globals['_INTENTROUTER']._serialized_end=358
# @@protoc_insertion_point(module_scope)
